CREATE TABLE conversations (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    type NVARCHAR(20) NOT NULL DEFAULT 'DIRECT',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT pk_conversations PRIMARY KEY CLUSTERED (id),
    CONSTRAINT ck_conversations_type CHECK (type IN ('DIRECT', 'GROUP'))
);
